---
title: "miniProject4"
author: "Christina Lyu & Sicong Li (using Github^[Github link: https://github.com/ChristinaLyu/miniProject3.git])"
date: "4/26/2018"
output: 
  html_document:
    code_folding: hide
    df_print: paged
    theme: cosmo
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mdsr)
library(RMySQL)
library(ggplot2)
db <- dbConnect_scidb(dbname = "imdb")
class(db)
```


```{r message = FALSE, warning = FALSE}
#The TV shows and the production companies with highest reviews ranked by year
tv_rank <- db %>%
  dbGetQuery("SELECT distinct t.id, t.title, t.production_year, n.name,
  mi1.info AS votes, mi2.info AS rating
FROM title t
JOIN movie_info_idx AS mi1 ON mi1.movie_id = t.id
JOIN movie_info_idx AS mi2 ON mi2.movie_id = t.id
join movie_companies as c on c.movie_id = t.id
join company_name as n on n.id = c.company_id
WHERE t.kind_id = 2
  AND mi1.info_type_id = 100
  AND mi2.info_type_id = 101
  AND mi1.info > 100000
ORDER BY t.production_year desc;")
tv_rank
```

```{r warning = FALSE, message = FALSE}
tv_all <- 
  db %>%
  dbGetQuery("SELECT distinct t.id, t.title, t.production_year, n.name,
  mi1.info AS votes, mi2.info AS rating
FROM title t
JOIN movie_info_idx AS mi1 ON mi1.movie_id = t.id
JOIN movie_info_idx AS mi2 ON mi2.movie_id = t.id
join movie_companies as c on c.movie_id = t.id
join company_name as n on n.id = c.company_id
WHERE t.kind_id = 2
  AND mi1.info_type_id = 100
  AND mi2.info_type_id = 101
ORDER BY t.production_year desc;")
tv_all
```

```{r}
company_all <- 
  db %>%
  dbGetQuery("SELECT name, count(*) as count, avg(mi1.info) as avg_votes, avg(mi2.info) as avg_rating
FROM title t
JOIN movie_info_idx AS mi1 ON mi1.movie_id = t.id
JOIN movie_info_idx AS mi2 ON mi2.movie_id = t.id
join movie_companies as c on c.movie_id = t.id
join company_name as n on n.id = c.company_id
WHERE t.kind_id = 2
  AND mi1.info_type_id = 100
  AND mi2.info_type_id = 101
GROUP BY name
order by avg_rating desc")
company_all
```

```{r warning = FALSE, message = FALSE}
  ggplot(data=company_all, aes(x=avg_votes, y=avg_rating)) +
  geom_bar(stat="identity")

```



```{r warning = FALSE, message = FALSE}
#the company that produced the best tv shows and their average rank and votes
company_count <- 
  db %>%
  dbGetQuery("SELECT name, count(*) as number, avg(mi1.info) as avg_votes, avg(mi2.info) as avg_rating
FROM title t
JOIN movie_info_idx AS mi1 ON mi1.movie_id = t.id
JOIN movie_info_idx AS mi2 ON mi2.movie_id = t.id
join movie_companies as c on c.movie_id = t.id
join company_name as n on n.id = c.company_id
WHERE t.kind_id = 2
  AND mi1.info_type_id = 100
  AND mi2.info_type_id = 101
  AND mi1.info > 100000
GROUP BY name
order by number desc")
company_count
```
```{r}
num_rating <-
  company_count %>%
  select(number, avg_rating) 
num_rating
```
















































